# User Management with SSH Key Configuration
# Feature: BCM-based Kubernetes Deployment via Kubespray
#
# Creates user accounts on BCM-managed nodes with supplied SSH public keys
# for passwordless authentication.

# =============================================================================
# Local Values for SSH Key Configuration
# =============================================================================

locals {
  # Combine generated SSH key with any additional user-supplied keys
  # The generated key from tls_private_key is always included for Ansible access
  all_ssh_public_keys_string = join("\n", concat(
    [tls_private_key.ssh_key.public_key_openssh],
    var.node_user_ssh_public_keys
  ))
}

# =============================================================================
# Automated User Creation
# =============================================================================
# NOTE: The BCM provider does not support user management resources.
# User creation is AUTOMATICALLY handled by an Ansible playbook that runs
# during Terraform apply (see user_creation.tf).
#
# The Ansible playbook creates the user with:
#   - Username: ansiblebcm (default, configurable via var.node_username)
#   - UID: 60000 (default, configurable via var.node_user_uid)
#   - GID: 60000 (default, configurable via var.node_user_gid)
#   - SSH keys: Generated by tls_private_key.ssh_key
#   - Sudo access: Passwordless sudo
#
# Requirements:
#   - var.admin_ssh_private_key_path must be set (path to admin's SSH key)
#   - var.admin_ssh_user should be 'root' or a user with passwordless sudo
#   - Set var.skip_user_creation=true if the user already exists on all nodes
#
# Manual alternative: Run scripts/create-user.sh before Terraform apply

# =============================================================================
# Outputs
# =============================================================================

output "expected_user_config" {
  description = "Expected user configuration for BCM nodes (must be created manually or via script)"
  value = {
    username       = var.node_username
    home_directory = var.node_user_home_dir != null ? var.node_user_home_dir : "/home/${var.node_username}"
    uid            = var.node_user_uid
    gid            = var.node_user_gid
    shell          = var.node_user_shell
    ssh_keys_count = length(compact(split("\n", local.all_ssh_public_keys_string)))
  }
}

output "user_ssh_public_key" {
  description = "The generated SSH public key configured for node users"
  value       = tls_private_key.ssh_key.public_key_openssh
}
